mutation BulkCreateProductVariants($productId: ID!, $variants: [ProductVariantsBulkInput!]!) {
  productVariantsBulkCreate(variants: $variants, productId: $productId, strategy:REMOVE_STANDALONE_VARIANT ) {
    productVariants {
      id
    }
    userErrors {
      field
      message
    }
  }
}