mutation CreateFiles($files: [FileCreateInput!]!) {
  fileCreate(files: $files) {
    files {
      id
      preview {
        image {
          id
          url
        }
      }
    }
    userErrors {
      code
      field
      message
    }
  }
}