mutation CreateMetaobjectDefinition($input: MetaobjectDefinitionCreateInput!) {
    metaobjectDefinitionCreate(definition: $input) {
        metaobjectDefinition{
            id
            type
        }
        userErrors {
            field
            message
        }
    }
}