mutation DeleteMetafield($input: [MetafieldIdentifierInput!]!) {
  metafieldsDelete(metafields: $input) {
    deletedMetafields {
      ownerId
      namespace
      key
    }
    userErrors {
      field
      message
    }
  }
}